#ifndef _FAULT_CODE_H_
#define _FAULT_CODE_H_

typedef enum{
    RET_OK = 0,
    RET_NULL_POINTER,
    RET_OPEN_FILE_FAILED,
    RET_READ_FILE_FAILED,
    RET_PARSER_JSON_FAILED,
    RET_GET_COMMAND_FAILED,
    RET_INDEX_OUT_OF_RANGE,
    RET_PLAY_AUDIO_FAILED
}E_FAULT_CODE;

#endif